language: ruby
rvm:
- 2.4.6
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - GIT_NAME=ragiragi
  - GIT_EMAIL=ragiragi@hanmail.net
  - secure: AFRO5sp65TAMI4ASl1+KsuGQlhP6LMrW8Bc8s27aGJJZNwBGSx7cd0wz+uhtilhUAapM7P4EJAosZHzUZdKZoad4tDdLGYvODhNcPc93eWSyw2JfZXeeIznOQcb+gC59kbGdniyBFxh3kAA5H6wImwqg3OAAGmYyDDfvwyI3XsksZTHQmJm///K5PCKfHCSj1IkDX1/L37nWpxLyjCPK+/Np7Ex6lDkN9L10gjvjyh7x69TyRBJTzYi4fVWf6oWx4ghhnJosUhb2FTm4HoMx5DLbZRVwr3wvlRcQ2Mwne8XyGjYozk3ctcSLiJ7WTC2xe0DoNAJHh2dCyAB5RqLqSeHINHizAIo4kN+uVsuBStASSMQg6aaBEm7X0AUfTtTAXR9x+BiB1fLIG/JHiQiJnxP9kjxCDro0MH/F34gb2ApS6fT17rhIjhbE3RiZBAMu4wr0wbl+fZ0fZKHLPD5Ik8BvbfMIUNlyItOBa8DQsh+onHPktd9rDvka0OcFp9XLNjj+UwHhQLkLukRcmCSTgbsAlKMJTUkTeiqaXz370lp1KeWrzz5e3Va3AprBCvK4qGa6NpxFhMtiiVdLOBAW9hIFn1zsj4pS+HXlzdB3rlYdccgT1Rc9iv9UUWOuko5lBLIB1jFZBcmUjru9h41m69rvK3CI4HszZGbu6GRV4t8=
